# Website settings
title: Eshwar S R
description: >- # this means to ignore newlines until "baseurl:"
  You've reached personal website of Eshwar S R.
baseurl:  ""
url: "http://EshwarSR.github.io/homepage"
author:  # change following line to your infomation.
  name: Eshwar S R  # Be used at blog posts' author.
  first_name: Eshwar  # Be used at index page about me section.
  last_name: S R  # Be used at index page about me section.
  avatar: /static/assets/img/landing/myphoto.jpg  # upload your avatar at directory and edit it.
  github_username: EshwarSR  # Leave blank if you don't have now
  linkedin_id: eshwarsr # Leave blank if you don't have now
  email: sr.eshwar07@gmail.com  # Leave blank if you don't have now
  cv:  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - icon: python
      name: icon-python
      source: mfizz
    - icon: aws
      name: fa-aws
      source: font-awesome
    - icon: linux
      name: fa-linux
      source: font-awesome
    - icon: github
      name: fa-github-square
      source: font-awesome
    - icon: php
      name: icon-php
      source: mfizz
    - icon: mongodb
      name: icon-mongodb
      source: mfizz
    - icon: docker
      name: devicon-docker-plain
      source: devicon
    - icon: redis
      name: icon-redis
      source: mfizz

  skill_icon2:
    - icon: html
      name: fa-html5
      source: font-awesome
    - icon: javascript
      name: icon-javascript
      source: mfizz
    - icon: jquery
      name: icon-jquery
      source: mfizz
    - icon: angular
      name: icon-angular
      source: mfizz
    - icon: css3
      name: icon-css3
      source: mfizz
    - icon: bootstrap
      name: devicon-bootstrap-plain-wordmark
      source: devicon
    - icon: jenkins
      name: fa-jenkins
      source: font-awesome
    - icon: shell
      name: icon-shell
      source: mfizz

  desc: "I completed my BE in Computer science from PESIT in 2016, where I cemented my fundamentals of computer science and also got a good introduction to interesting domains like Machine Learning, Natural Language Processing (NLP) and BigData.<br><br>I joined Intuit as DevOps Engineer as part of campus hiring. I got a great grasp of infrastructure, automation, CICD, Docker and cloud (especially AWS). My responsibilities included providing and also implementing CICD solutions both on-prim and cloud. Also, built many tools which facilitates internal teams with traffic management in data centers, automatic restoration of failed services, tracing the failure of an order, evaluating CICD progress etc.<br><br> After 2 years journey at Intuit, I joined Kenome - a nascent but extremely driven core AI startup helping enterprises make sense of dark data using cutting-edge Machine Learning, NLP and Knowledge Graphs. <br><br> Currently I am trying to build fundamentals in the field of AI - Supervised Learning, Unsupervised learning and Reinforcement Learning. I'm familiar with algorithms like Linear Regression, Logistic Regression, Decision Trees, Random Forests, Support Vector Machines, Neural Networks (ex CNN, RNN) and Probabilistic Graphical Models.<br><br> In the long run I wish to build products which solve some of the harder problems which AI is trying to solve."

#other pages
include: ["_pages"]

# comment
# disqus: 
#   name: Eshwar

# analytics
## google analytics
ga:
  id: UA-133822481-1

## google optimize
#go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rogue
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rogue

plugins:
  - jekyll-feed 
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll_inline_highlight
  - jekyll-last-modified-at
